theme: jekyll-theme-minimal
title:  How Has Political Sentiment Changed Over the Course of the Pandemic?
description: 
show_downloads: True
navigation:
  # - title: Home
  #   url: /
  # - title: Example
  #   url: example
